version: '3'
services:
  plataforma:
    image: ghost:1-alpine
    restart: always
    ports:
      - 2368:2368
    environment:
      - database_client=mysql
      - database__connection__database=ghost
      - database__connection__host=database
      - database__connection__user=pessoaUsuária
      - database__connection__password=senha123
    networks:
      - my-network
    depends_on:
      - database
  database:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=senha123
    volumes:
      - dados:/var/lib/mysql
    networks:
      - my-network

volumes:
  dados:

networks:
  my-network:
